stages:
 - deploy

deploy_digitalocean_prod:
    type: deploy
    image: ubuntu
    environment: production
    script:
      - apt update -y
      - apt install -y sshpass
      - rm -rf ../groceryapi
      - mkdir ../groceryapi
      - chmod -R +r ../groceryapi
      - cp -r . ../groceryapi
      - sshpass -p $SERVER_TOCKEN scp -o stricthostkeychecking=no -r ../groceryapi/ root@$SERVER_IP:/root/.
      - sshpass -p $SERVER_TOCKEN ssh -o StrictHostKeyChecking=no root@$SERVER_IP "cd groceryapi; npm i; export NODE_ENV=production; export PORT=3000; export HOST=127.0.0.1; npm run build; pm2 delete groceryapi; pm2 start 'dist/main.js' --name 'groceryapi';"
    only:
      - master


deploy_digitalocean_testing:
    type: deploy
    image: ubuntu
    environment: development
    script:
      - apt update -y
      - apt install -y sshpass
      - rm -rf ../grocerytestingapi
      - mkdir ../grocerytestingapi
      - chmod -R +r ../grocerytestingapi
      - cp -r . ../grocerytestingapi
      - sshpass -p $SERVER_TOCKEN scp -o stricthostkeychecking=no -r ../grocerytestingapi/ root@$SERVER_IP:/root/.
      - sshpass -p $SERVER_TOCKEN ssh -o StrictHostKeyChecking=no root@$SERVER_IP "cd grocerytestingapi; npm i; export NODE_ENV=development; export PORT=4000; export HOST=127.0.0.1; npm run build; pm2 delete grocerytestingapi; pm2 start 'dist/main.js' --name 'grocerytestingapi';"
    only:
      - testing
